# pull official base image
FROM node:13.12.0-alpine

# create directory
RUN mkdir -p /app/src

# set working directory
WORKDIR /app/src

# copy dependencies
COPY package.json

# install app dependencies
RUN npm install

# add app
COPY . .

# port
EXPOSE 3000

# start app
CMD ["npm", "start"]