version: "3"
services: 
    travel-app:
        build: .
        stdin_open: true
        ports: 
            - "3000:3000"
        volumes:
            - ./src:/app/src:ro
        environment:
            - CHOKIDAR_USEPOLLING=true
        # env_files:
        #     - ./.env